{% set name = "molcomplib" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molcomplib-{{ version }}.tar.gz
  sha256: 31d3d8645c0363611891ea2409df28bfa719dc0a7bd26f70c0a9e5ba10158243

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - rdkit
    - numpy

test:
  imports:
    - molcomplib
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/sergsb/molcomplib
  summary: A python library and the standatrized model for the navigation in chemical space. It consists of parametric t-SNE model pretrained on large dataset of bioactive compounds. This library is a part of MolCompass project.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sergsb
