{% set name = "molcomplib" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molcomplib-{{ version }}.tar.gz
  sha256: 22d48e30e726edf95c21b0d79ed7616ee8f803b6105c971413cc9980bf4ce72c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - rdkit
    - numpy

test:
  imports:
    - molcomplib
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/sergsb/molcomplib
  summary: A python library and the standatrized model for the navigation in chemical space. It consists of parametric t-SNE model pretrained on large dataset of bioactive compounds. This library is a part of MolCompass project.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sergsb
